In [1]:
import pandas as pd
import glob
import os

In [3]:
trial_df = pd.read_csv('C:/Users/lucky/Documents/Tutorial/PoC/AllVAERSDataCSVS/2022VAERSDATA.csv', encoding = "latin-1")
trial_df.head()

C:\Users\lucky\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (12) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,CUR_ILL,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES
0,1996873,01/01/2022,CA,NaN,NaN,NaN,U,NaN,This spontaneous report was received from a ph...,NaN,...,NaN,NaN,NaN,US0095075132112USA007320,2,12/31/2021,NaN,NaN,NaN,NaN
1,1996874,01/01/2022,NaN,NaN,NaN,NaN,U,NaN,SUSPECTED CLINICAL VACCINATION FAILURE; SUSPEC...,NaN,...,NaN,NaN,NaN,USJNJFOC20211263430,2,01/01/2022,NaN,NaN,NaN,NaN
2,1996875,01/01/2022,OH,NaN,NaN,NaN,M,NaN,SUSPECTED CLINICAL VACCINATION FAILURE; SUSPEC...,NaN,...,NaN,NaN,NaN,USJNJFOC20211266010,2,01/01/2022,NaN,NaN,NaN,NaN
3,1996876,01/01/2022,MS,34.0,NaN,NaN,F,NaN,Irregular menstrual cycle.; period extremely h...,NaN,...,NaN,Comments: List of non-encoded Patient Relevant...,NaN,USPFIZER INC202101162241,2,12/31/2021,NaN,NaN,NaN,NaN
4,1996877,01/01/2022,CT,NaN,NaN,NaN,F,NaN,Breakthrough and heavy periods; longer period ...,NaN,...,NaN,NaN,NaN,USPFIZER INC202101281356,2,12/31/2021,NaN,NaN,NaN,NaN

In [7]:
trial_df1 = pd.read_csv('C:/Users/lucky/Documents/Tutorial/PoC/AllVAERSDataCSVS/1990VAERSDATA.csv', encoding = "latin-1")
trial_df1.head()

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,CUR_ILL,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES
0,25001,07/02/1990,WI,0.2,NaN,NaN,F,NaN,Loud intense cry with screaming for 1 1/2 hrs....,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
1,25003,07/02/1990,TX,0.8,NaN,NaN,M,NaN,"Hypotonic, Hyporesponsive episode, Infant died...",Y,...,NaN,NaN,~ ()~~~In patient,NaN,1,NaN,NaN,NaN,NaN,NaN
2,25004,07/02/1990,NY,0.9,NaN,NaN,M,NaN,"Pt developed chills for approx. 1 hr, felt ach...",NaN,...,NaN,NaN,~ ()~~~In patient,890269201,1,NaN,NaN,NaN,NaN,NaN
3,25005,07/02/1990,OK,NaN,NaN,NaN,U,NaN,7 patients within 2 weeks have reported joint ...,NaN,...,NaN,NaN,~ ()~~~In patient,890277901,1,NaN,NaN,NaN,NaN,NaN
4,25006,07/02/1990,OH,16.0,16.0,NaN,F,NaN,16 yr old female feeling faint & then had seiz...,NaN,...,NaN,no hx of local or systemic rxns,~ ()~~~In patient,890278001,1,NaN,NaN,NaN,NaN,NaN

In [6]:
non_dom_df = pd.read_csv('C:/Users/lucky/Documents/Tutorial/PoC/AllVAERSDataCSVS/NonDomesticVAERSDATA.csv', encoding = "latin-1", low_memory=False)
non_dom_df.head()

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,CUR_ILL,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES
0,25002,07/02/1990,FR,82.0,NaN,NaN,M,NaN,"23 hrs post vaccination, developed seizures fo...",NaN,...,NaN,"Senile dementia, Diabetes mellitus, seizures",~ ()~~~In patient,WAES90040535,1,NaN,NaN,NaN,NaN,NaN
1,25010,07/02/1990,FR,1.7,NaN,NaN,M,NaN,"17 mon. male, received 29Oct89 MMR vaccine 1 d...",Y,...,NaN,NaN,~ ()~~~In patient,WAES90060362,1,NaN,NaN,NaN,NaN,NaN
2,25011,07/02/1990,FR,5.0,NaN,NaN,F,NaN,Approx. 1 hr /p Engerix-B vaccine given became...,NaN,...,NaN,"No hx in the pregnacy, neonatal period, family...",~ ()~~~In patient,EBWWMA010932,1,NaN,NaN,NaN,NaN,NaN
3,25064,07/02/1990,FR,NaN,NaN,NaN,F,NaN,mother vaccinated w/ Rubella 1979. Pregancey u...,NaN,...,NaN,NaN,~ ()~~~In patient,WAES90060087,1,NaN,NaN,NaN,NaN,NaN
4,25055,07/09/1990,FR,54.0,NaN,NaN,F,NaN,Hepatic pain. Increase liver fx test. Nause c...,NaN,...,NaN,On medication for the treatment of tuberculosi...,~ ()~~~In patient,EBWWMA010375,1,NaN,NaN,NaN,NaN,NaN

## Reading all the files

In [8]:
file_path = 'C:/Users/lucky/Documents/Tutorial/PoC/AllVAERSDataCSVS'
file_list = os.listdir(file_path)
file_list

['1990VAERSDATA.csv',
 '1990VAERSSYMPTOMS.csv',
 '1990VAERSVAX.csv',
 '1991VAERSDATA.csv',
 '1991VAERSSYMPTOMS.csv',
 '1991VAERSVAX.csv',
 '1992VAERSDATA.csv',
 '1992VAERSSYMPTOMS.csv',
 '1992VAERSVAX.csv',
 '1993VAERSDATA.csv',
 '1993VAERSSYMPTOMS.csv',
 '1993VAERSVAX.csv',
 '1994VAERSDATA.csv',
 '1994VAERSSYMPTOMS.csv',
 '1994VAERSVAX.csv',
 '1995VAERSDATA.csv',
 '1995VAERSSYMPTOMS.csv',
 '1995VAERSVAX.csv',
 '1996VAERSDATA.csv',
 '1996VAERSSYMPTOMS.csv',
 '1996VAERSVAX.csv',
 '1997VAERSDATA.csv',
 '1997VAERSSYMPTOMS.csv',
 '1997VAERSVAX.csv',
 '1998VAERSDATA.csv',
 '1998VAERSSYMPTOMS.csv',
 '1998VAERSVAX.csv',
 '1999VAERSDATA.csv',
 '1999VAERSSYMPTOMS.csv',
 '1999VAERSVAX.csv',
 '2000VAERSDATA.csv',
 '2000VAERSSYMPTOMS.csv',
 '2000VAERSVAX.csv',
 '2001VAERSDATA.csv',
 '2001VAERSSYMPTOMS.csv',
 '2001VAERSVAX.csv',
 '2002VAERSDATA.csv',
 '2002VAERSSYMPTOMS.csv',
 '2002VAERSVAX.csv',
 '2003VAERSDATA.csv',
 '2003VAERSSYMPTOMS.csv',
 '2003VAERSVAX.csv',
 '2004VAERSDATA.csv',
 '2004VAERSSYMPTOMS.csv',
 '2004VAERSVAX.csv',
 '2005VAERSDATA.csv',
 '2005VAERSSYMPTOMS.csv',
 '2005VAERSVAX.csv',
 '2006VAERSDATA.csv',
 '2006VAERSSYMPTOMS.csv',
 '2006VAERSVAX.csv',
 '2007VAERSDATA.csv',
 '2007VAERSSYMPTOMS.csv',
 '2007VAERSVAX.csv',
 '2008VAERSDATA.csv',
 '2008VAERSSYMPTOMS.csv',
 '2008VAERSVAX.csv',
 '2009VAERSDATA.csv',
 '2009VAERSSYMPTOMS.csv',
 '2009VAERSVAX.csv',
 '2010VAERSDATA.csv',
 '2010VAERSSYMPTOMS.csv',
 '2010VAERSVAX.csv',
 '2011VAERSDATA.csv',
 '2011VAERSSYMPTOMS.csv',
 '2011VAERSVAX.csv',
 '2012VAERSDATA.csv',
 '2012VAERSSYMPTOMS.csv',
 '2012VAERSVAX.csv',
 '2013VAERSDATA.csv',
 '2013VAERSSYMPTOMS.csv',
 '2013VAERSVAX.csv',
 '2014VAERSDATA.csv',
 '2014VAERSSYMPTOMS.csv',
 '2014VAERSVAX.csv',
 '2015VAERSDATA.csv',
 '2015VAERSSYMPTOMS.csv',
 '2015VAERSVAX.csv',
 '2016VAERSDATA.csv',
 '2016VAERSSYMPTOMS.csv',
 '2016VAERSVAX.csv',
 '2017VAERSDATA.csv',
 '2017VAERSSYMPTOMS.csv',
 '2017VAERSVAX.csv',
 '2018VAERSDATA.csv',
 '2018VAERSSYMPTOMS.csv',
 '2018VAERSVAX.csv',
 '2019VAERSDATA.csv',
 '2019VAERSSYMPTOMS.csv',
 '2019VAERSVAX.csv',
 '2020VAERSDATA.csv',
 '2020VAERSSYMPTOMS.csv',
 '2020VAERSVAX.csv',
 '2021VAERSDATA.csv',
 '2021VAERSSYMPTOMS.csv',
 '2021VAERSVAX.csv',
 '2022VAERSDATA.csv',
 '2022VAERSSYMPTOMS.csv',
 '2022VAERSVAX.csv',
 'NonDomesticVAERSDATA.csv',
 'NonDomesticVAERSSYMPTOMS.csv',
 'NonDomesticVAERSVAX.csv']

## Reading via glob

In [ ]:
# vaers_all_year = glob.glob('*VAERSDATA')

In [9]:
# setting the path for joining multiple files
files = os.path.join("C:/Users/lucky/Documents/Tutorial/PoC/AllVAERSDataCSVS", "*VAERSDATA.csv")

# list of merged files returned
files = glob.glob(files)

In [10]:
print("Resultant CSV after joining all CSV files at a particular location...");

# joining files with concat and read_csv
df = pd.concat(map(pd.read_csv, files), ignore_index=True)
print(df)

Resultant CSV after joining all CSV files at a particular location...

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 100874: invalid start byte

## Method 2

In [24]:
os.chdir("C:/Users/lucky/Documents/Tutorial/PoC/AllVAERSDataCSVS")
all_filenames = [i for i in glob.glob('*VAERSDATA.{}'.format('csv'))]

In [25]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f, encoding='latin-1', low_memory = False) for f in all_filenames])
#export to csv
combined_csv.to_csv( "combined_dataset.csv", index=False)

In [41]:
incoming_path = os.chdir("C:/Users/lucky/Documents/Tutorial/PoC/AllVAERSDataCSVS")
outgoing_path = "C:/Users/lucky/Documents/Tutorial/PoC/Combined_Dataset/"
file_str = '*VAERSDATA'
data_format = 'csv'

In [39]:
file_str + '.' + data_format

'*VAERSDATA.csv'

In [43]:
out_file_name = 'Combined_VAERSDATA'

In [44]:
print(outgoing_path + out_file_name + '.' + data_format)

C:/Users/lucky/Documents/Tutorial/PoC/Combined_Dataset/Combined_VAERSDATA.csv

In [45]:
def concat_files(in_path, file_str, encoding, data_format, out_path, out_file_name):
    all_files = [i for i in glob.glob(file_str + '.' + data_format)]
    combined_data = pd.concat([pd.read_csv(f, encoding='latin-1', low_memory = False) for f in all_files])
    
    return combined_data.to_csv(outgoing_path + out_file_name + '.' + data_format, index=False)

In [46]:
concat_files(incoming_path, file_str, 'latin-1', data_format, outgoing_path, out_file_name)

In [18]:
combined_df = pd.read_csv('C:/Users/lucky/Documents/Tutorial/PoC/combined_csv.csv', encoding = "latin-1", low_memory = False)
combined_df.head()

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,SYMPTOMVERSION4,SYMPTOM5,SYMPTOMVERSION5,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,25001,07/02/1990,WI,0.2,NaN,NaN,F,NaN,Loud intense cry with screaming for 1 1/2 hrs....,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,25003,07/02/1990,TX,0.8,NaN,NaN,M,NaN,"Hypotonic, Hyporesponsive episode, Infant died...",Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,25004,07/02/1990,NY,0.9,NaN,NaN,M,NaN,"Pt developed chills for approx. 1 hr, felt ach...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25005,07/02/1990,OK,NaN,NaN,NaN,U,NaN,7 patients within 2 weeks have reported joint ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,25006,07/02/1990,OH,16.0,16.0,NaN,F,NaN,16 yr old female feeling faint & then had seiz...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
print(sorted(combined_df['VAERS_ID'].unique()))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [21]:
combined_df['VAERS_ID'].unique()

array([  25001,   25003,   25004, ..., 2498813, 2498814, 2498815],
      dtype=int64)

In [23]:
combined_df[combined_df['VAERS_ID'] == 25002]

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,SYMPTOMVERSION4,SYMPTOM5,SYMPTOMVERSION5,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
5917001,25002,07/02/1990,FR,82.0,NaN,NaN,M,NaN,"23 hrs post vaccination, developed seizures fo...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6595572,25002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7603890,25002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,PPV,MERCK & CO. INC.,M0870,UNK,IM,NaN,PNEUMO (PNEUMOVAX)

In [27]:
new_df = pd.read_csv('C:/Users/lucky/Documents/Tutorial/PoC/AllVAERSDataCSVS/combined_dataset.csv', encoding = "latin-1", low_memory = False)
new_df.head()

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,CUR_ILL,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES
0,25001,07/02/1990,WI,0.2,NaN,NaN,F,NaN,Loud intense cry with screaming for 1 1/2 hrs....,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
1,25003,07/02/1990,TX,0.8,NaN,NaN,M,NaN,"Hypotonic, Hyporesponsive episode, Infant died...",Y,...,NaN,NaN,~ ()~~~In patient,NaN,1,NaN,NaN,NaN,NaN,NaN
2,25004,07/02/1990,NY,0.9,NaN,NaN,M,NaN,"Pt developed chills for approx. 1 hr, felt ach...",NaN,...,NaN,NaN,~ ()~~~In patient,890269201,1,NaN,NaN,NaN,NaN,NaN
3,25005,07/02/1990,OK,NaN,NaN,NaN,U,NaN,7 patients within 2 weeks have reported joint ...,NaN,...,NaN,NaN,~ ()~~~In patient,890277901,1,NaN,NaN,NaN,NaN,NaN
4,25006,07/02/1990,OH,16.0,16.0,NaN,F,NaN,16 yr old female feeling faint & then had seiz...,NaN,...,NaN,no hx of local or systemic rxns,~ ()~~~In patient,890278001,1,NaN,NaN,NaN,NaN,NaN

In [29]:
new_df[new_df['VAERS_ID'] == 25002]

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,CUR_ILL,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES
1673991,25002,07/02/1990,FR,82.0,NaN,NaN,M,NaN,"23 hrs post vaccination, developed seizures fo...",NaN,...,NaN,"Senile dementia, Diabetes mellitus, seizures",~ ()~~~In patient,WAES90040535,1,NaN,NaN,NaN,NaN,NaN

In [32]:
a = new_df['VAERS_ID'].unique()

In [34]:
a.sort()
print(a)

[  25001   25002   25003 ... 2498869 2498873 2498935]

In [35]:
len(a)

2352562

In [47]:
vaers_data = pd.read_csv('C:/Users/lucky/Documents/Tutorial/PoC/Combined_Dataset/Combined_VAERSDATA.csv', encoding = 'latin-1', low_memory = False)

In [49]:
vaers_data = vaers_data.sort_values(by = ['VAERS_ID'])

In [50]:
vaers_data.head()

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,CUR_ILL,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES
0,25001,07/02/1990,WI,0.2,NaN,NaN,F,NaN,Loud intense cry with screaming for 1 1/2 hrs....,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
1673991,25002,07/02/1990,FR,82.0,NaN,NaN,M,NaN,"23 hrs post vaccination, developed seizures fo...",NaN,...,NaN,"Senile dementia, Diabetes mellitus, seizures",~ ()~~~In patient,WAES90040535,1,NaN,NaN,NaN,NaN,NaN
1,25003,07/02/1990,TX,0.8,NaN,NaN,M,NaN,"Hypotonic, Hyporesponsive episode, Infant died...",Y,...,NaN,NaN,~ ()~~~In patient,NaN,1,NaN,NaN,NaN,NaN,NaN
2,25004,07/02/1990,NY,0.9,NaN,NaN,M,NaN,"Pt developed chills for approx. 1 hr, felt ach...",NaN,...,NaN,NaN,~ ()~~~In patient,890269201,1,NaN,NaN,NaN,NaN,NaN
3,25005,07/02/1990,OK,NaN,NaN,NaN,U,NaN,7 patients within 2 weeks have reported joint ...,NaN,...,NaN,NaN,~ ()~~~In patient,890277901,1,NaN,NaN,NaN,NaN,NaN

In [51]:
v_data = pd.read_csv('C:/Users/lucky/Documents/Tutorial/PoC/Combined_Dataset/Combined_VAERSDATA.csv', encoding = 'latin-1')
v_data.head()

C:\Users\lucky\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (7,12,15,23,27,30,31,32,33,34) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,CUR_ILL,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES
0,25001,07/02/1990,WI,0.2,NaN,NaN,F,NaN,Loud intense cry with screaming for 1 1/2 hrs....,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
1,25003,07/02/1990,TX,0.8,NaN,NaN,M,NaN,"Hypotonic, Hyporesponsive episode, Infant died...",Y,...,NaN,NaN,~ ()~~~In patient,NaN,1,NaN,NaN,NaN,NaN,NaN
2,25004,07/02/1990,NY,0.9,NaN,NaN,M,NaN,"Pt developed chills for approx. 1 hr, felt ach...",NaN,...,NaN,NaN,~ ()~~~In patient,890269201,1,NaN,NaN,NaN,NaN,NaN
3,25005,07/02/1990,OK,NaN,NaN,NaN,U,NaN,7 patients within 2 weeks have reported joint ...,NaN,...,NaN,NaN,~ ()~~~In patient,890277901,1,NaN,NaN,NaN,NaN,NaN
4,25006,07/02/1990,OH,16.0,16.0,NaN,F,NaN,16 yr old female feeling faint & then had seiz...,NaN,...,NaN,no hx of local or systemic rxns,~ ()~~~In patient,890278001,1,NaN,NaN,NaN,NaN,NaN

In [52]:
v_vax = pd.read_csv('C:/Users/lucky/Documents/Tutorial/PoC/Combined_Dataset/Combined_VAERSVAX.csv', encoding = 'latin-1', low_memory=False)
v_vax.head()

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,25001,DTP,CONNAUGHT LABORATORIES,9Q01042,UNK,IM,NaN,DTP (NO BRAND NAME)
1,25003,DTP,LEDERLE LABORATORIES,259962,4,IM,NaN,DTP (TRI-IMMUNOL)
2,25003,OPV,PFIZER\WYETH,241950,4,PO,MO,"POLIO VIRUS, ORAL (ORIMUNE)"
3,25004,OPV,PFIZER\WYETH,232961,UNK,NaN,NaN,"POLIO VIRUS, ORAL (ORIMUNE)"
4,25005,TD,LEDERLE LABORATORIES,247955,UNK,IM,NaN,TD ADSORBED (NO BRAND NAME)

In [53]:
v_symptom = pd.read_csv('C:/Users/lucky/Documents/Tutorial/PoC/Combined_Dataset/Combined_VAERSSYMPTOMS.csv', encoding = 'latin-1', low_memory=False)
v_symptom.head()

,VAERS_ID,SYMPTOM1,SYMPTOMVERSION1,SYMPTOM2,SYMPTOMVERSION2,SYMPTOM3,SYMPTOMVERSION3,SYMPTOM4,SYMPTOMVERSION4,SYMPTOM5,SYMPTOMVERSION5
0,25001,Agitation,8.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,25003,Delirium,8.1,Hypokinesia,8.1,Hypotonia,8.1,NaN,NaN,NaN,NaN
2,25004,Chills,8.1,Dermatitis contact,8.1,Oedema genital,8.1,Pelvic pain,8.1,NaN,NaN
3,25005,Arthritis,8.1,Injection site oedema,8.1,Injection site reaction,8.1,NaN,NaN,NaN,NaN
4,25006,Convulsion,8.1,Dizziness,8.1,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#  df3.merge(df1, on='place_id', how='left')

In [ ]:
# v_data.merge(v_vax, on='VAERS_ID', how=)

In [54]:
v_data_vax = v_data.merge(v_vax, on='VAERS_ID', how='left')
v_data_vax.head()

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,OFC_VISIT,ER_ED_VISIT,ALLERGIES,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,25001,07/02/1990,WI,0.2,NaN,NaN,F,NaN,Loud intense cry with screaming for 1 1/2 hrs....,NaN,...,NaN,NaN,NaN,DTP,CONNAUGHT LABORATORIES,9Q01042,UNK,IM,NaN,DTP (NO BRAND NAME)
1,25003,07/02/1990,TX,0.8,NaN,NaN,M,NaN,"Hypotonic, Hyporesponsive episode, Infant died...",Y,...,NaN,NaN,NaN,DTP,LEDERLE LABORATORIES,259962,4,IM,NaN,DTP (TRI-IMMUNOL)
2,25003,07/02/1990,TX,0.8,NaN,NaN,M,NaN,"Hypotonic, Hyporesponsive episode, Infant died...",Y,...,NaN,NaN,NaN,OPV,PFIZER\WYETH,241950,4,PO,MO,"POLIO VIRUS, ORAL (ORIMUNE)"
3,25004,07/02/1990,NY,0.9,NaN,NaN,M,NaN,"Pt developed chills for approx. 1 hr, felt ach...",NaN,...,NaN,NaN,NaN,OPV,PFIZER\WYETH,232961,UNK,NaN,NaN,"POLIO VIRUS, ORAL (ORIMUNE)"
4,25005,07/02/1990,OK,NaN,NaN,NaN,U,NaN,7 patients within 2 weeks have reported joint ...,NaN,...,NaN,NaN,NaN,TD,LEDERLE LABORATORIES,247955,UNK,IM,NaN,TD ADSORBED (NO BRAND NAME)

In [55]:
v_final = v_data_vax.merge(v_symptom, on = 'VAERS_ID', how = 'left')
v_final.head()

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,SYMPTOM1,SYMPTOMVERSION1,SYMPTOM2,SYMPTOMVERSION2,SYMPTOM3,SYMPTOMVERSION3,SYMPTOM4,SYMPTOMVERSION4,SYMPTOM5,SYMPTOMVERSION5
0,25001,07/02/1990,WI,0.2,NaN,NaN,F,NaN,Loud intense cry with screaming for 1 1/2 hrs....,NaN,...,Agitation,8.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,25003,07/02/1990,TX,0.8,NaN,NaN,M,NaN,"Hypotonic, Hyporesponsive episode, Infant died...",Y,...,Delirium,8.1,Hypokinesia,8.1,Hypotonia,8.1,NaN,NaN,NaN,NaN
2,25003,07/02/1990,TX,0.8,NaN,NaN,M,NaN,"Hypotonic, Hyporesponsive episode, Infant died...",Y,...,Delirium,8.1,Hypokinesia,8.1,Hypotonia,8.1,NaN,NaN,NaN,NaN
3,25004,07/02/1990,NY,0.9,NaN,NaN,M,NaN,"Pt developed chills for approx. 1 hr, felt ach...",NaN,...,Chills,8.1,Dermatitis contact,8.1,Oedema genital,8.1,Pelvic pain,8.1,NaN,NaN
4,25005,07/02/1990,OK,NaN,NaN,NaN,U,NaN,7 patients within 2 weeks have reported joint ...,NaN,...,Arthritis,8.1,Injection site oedema,8.1,Injection site reaction,8.1,NaN,NaN,NaN,NaN

In [56]:
v_final.shape

(3791944, 52)

In [57]:
print('v_data - ', v_data.shape)
print('v_vax - ', v_vax.shape)
print('v_symptom - ', v_symptom.shape)

v_data -  (2352562, 35)
v_vax -  (2856247, 8)
v_symptom -  (3136524, 11)

In [60]:
x = v_symptom['VAERS_ID'].value_counts()

In [61]:
print(x)

2304026    42
1891512    38
607782     38
2197542    32
2050891    32
           ..
1059191     1
1059189     1
1059188     1
1059187     1
1539847     1
Name: VAERS_ID, Length: 2352303, dtype: int64

In [63]:
v_symptom.loc[v_symptom['VAERS_ID'] == 2304026]

,VAERS_ID,SYMPTOM1,SYMPTOMVERSION1,SYMPTOM2,SYMPTOMVERSION2,SYMPTOM3,SYMPTOMVERSION3,SYMPTOM4,SYMPTOMVERSION4,SYMPTOM5,SYMPTOMVERSION5
2999570,2304026,Abdominal distension,25.0,Activated partial thromboplastin time normal,25.0,Alanine aminotransferase increased,25.0,Alopecia,25.0,Amenorrhoea,25.0
2999571,2304026,Anaemia megaloblastic,25.0,Angiogram cerebral normal,25.0,Angiogram pulmonary abnormal,25.0,Anti-Muellerian hormone level,25.0,Anti-cyclic citrullinated peptide antibody neg...,25.0
2999572,2304026,Anti-infective therapy,25.0,Anti-interferon antibody negative,25.0,Antibody test negative,25.0,Anticoagulant therapy,25.0,Antifungal treatment,25.0
2999573,2304026,Antimitochondrial antibody normal,25.0,Antinuclear antibody,25.0,Antinuclear antibody negative,25.0,Antiphospholipid antibodies negative,25.0,Antiplatelet therapy,25.0
2999574,2304026,Antiribosomal P antibody,25.0,Arthralgia,25.0,Aspartate aminotransferase increased,25.0,Asthenia,25.0,Bacterial test negative,25.0
2999575,2304026,Beta-2 glycoprotein antibody negative,25.0,Bilirubin conjugated increased,25.0,Biopsy bone marrow abnormal,25.0,Blood albumin decreased,25.0,Blood albumin increased,25.0
2999576,2304026,Blood bilirubin increased,25.0,Blood bilirubin unconjugated,25.0,Blood calcium decreased,25.0,Blood chloride normal,25.0,Blood cholinesterase increased,25.0
2999577,2304026,Blood creatine phosphokinase,25.0,Blood creatinine normal,25.0,Blood electrolytes,25.0,Blood fibrinogen decreased,25.0,Blood folate,25.0
2999578,2304026,Blood follicle stimulating hormone increased,25.0,Blood glucose normal,25.0,Blood grouping,25.0,Blood lactate dehydrogenase increased,25.0,Blood luteinising hormone increased,25.0
2999579,2304026,Blood potassium normal,25.0,Blood prolactin,25.0,Blood prolactin increased,25.0,Blood sodium normal,25.0,Blood testosterone,25.0
2999580,2304026,Blood urea decreased,25.0,Blood urea nitrogen/creatinine ratio,25.0,C-reactive protein increased,25.0,Carbon dioxide decreased,25.0,Cardiac dysfunction,25.0
2999581,2304026,Cardiac failure,25.0,Cardiac valve disease,25.0,Cardiolipin antibody negative,25.0,Cardiomegaly,25.0,Cell marker,25.0
2999582,2304026,Central nervous system lesion,25.0,Central venous catheterisation,25.0,Chest X-ray normal,25.0,Chlamydia test negative,25.0,Cholecystitis chronic,25.0
2999583,2304026,Chromaturia,25.0,Coagulation test,25.0,Computerised tomogram abdomen abnormal,25.0,Computerised tomogram thorax abnormal,25.0,Coombs direct test,25.0
2999584,2304026,Coombs direct test positive,25.0,Coombs test negative,25.0,Coombs test positive,25.0,Cough,25.0,Creatinine urine,25.0
2999585,2304026,Cyanosis,25.0,Cytogenetic analysis normal,25.0,Death,25.0,Decreased appetite,25.0,Demyelination,25.0
2999586,2304026,Differential white blood cell count abnormal,25.0,Diuretic therapy,25.0,Double stranded DNA antibody,25.0,Drug hypersensitivity,25.0,Drug-induced liver injury,25.0
2999587,2304026,Dyskinesia,25.0,Echocardiogram,25.0,Ejection fraction,25.0,Electrophoresis,25.0,Erythroid series abnormal,25.0
2999588,2304026,Face oedema,25.0,Feeling cold,25.0,Female sex hormone level,25.0,Fibrin D dimer,25.0,Full blood count,25.0
2999589,2304026,Fungal test negative,25.0,Gamma-glutamyltransferase increased,25.0,Gaze palsy,25.0,Globulin,25.0,Granulocyte count,25.0
2999590,2304026,Haemoglobin increased,25.0,Haemophagocytic lymphohistiocytosis,25.0,Heart rate increased,25.0,Heart valve incompetence,25.0,Hepatic function abnormal,25.0
2999591,2304026,Hepatitis B DNA assay positive,25.0,Hepatitis B core antibody positive,25.0,Hepatitis B surface antibody positive,25.0,Hepatitis C antibody negative,25.0,Hepatosplenomegaly,25.0
2999592,2304026,Histone antibody negative,25.0,Hormone therapy,25.0,Hypertriglyceridaemia,25.0,Hypoproteinaemia,25.0,Hyporesponsive to stimuli,25.0
2999593,2304026,Immunology test,25.0,Interleukin-2 receptor increased,25.0,International normalised ratio increased,25.0,Intra-abdominal fluid collection,25.0,Investigation,25.0
2999594,2304026,Joint swelling,25.0,Laboratory test abnormal,25.0,Leukaemoid reaction,25.0,Light chain analysis,25.0,Liver function test,25.0
2999595,2304026,Liver injury,25.0,Liver palpable,25.0,Liver-kidney microsomal antibody negative,25.0,Lymphadenopathy,25.0,Lymphadenopathy mediastinal,25.0
2999596,2304026,Lymphocyte count increased,25.0,Lymphoma,25.0,Magnetic resonance imaging head normal,25.0,Menstrual disorder,25.0,Mitral valve incompetence,25.0
2999597,2304026,Multiple organ dysfunction syndrome,25.0,Mycobacterium tuberculosis complex test negative,25.0,Mycoplasma test negative,25.0,Myeloproliferative neoplasm,25.0,N-terminal prohormone brain natriuretic peptid...,25.0
2999598,2304026,Natural killer cell activity test,25.0,Natural killer cell count,25.0,Natural killer cell count decreased,25.0,Night sweats,25.0,Non-compaction cardiomyopathy,25.0
2999599,2304026,Ocular icterus,25.0,Oedema,25.0,Oedema peripheral,25.0,Oestradiol,25.0,Ovarian failure,25.0
2999600,2304026,Parasitic test,25.0,Pathology test,25.0,Pelvic fluid collection,25.0,Pericardial effusion,25.0,Peripheral coldness,25.0
2999601,2304026,Plasmapheresis,25.0,Platelet count increased,25.0,Pleural effusion,25.0,Pneumonia,25.0,Polyserositis,25.0
2999602,2304026,Positron emission tomogram,25.0,Procalcitonin,25.0,Progesterone,25.0,Protein C decreased,25.0,Protein S decreased,25.0
2999603,2304026,Protein urine,25.0,Prothrombin level decreased,25.0,Prothrombin time prolonged,25.0,Prothrombin time ratio increased,25.0,Pruritus,25.0
2999604,2304026,Pulmonary arterial pressure increased,25.0,Pulmonary artery dilatation,25.0,Pulmonary embolism,25.0,Pulmonary hypertension,25.0,Pulmonary mass,25.0
2999605,2304026,Pulmonary valve incompetence,25.0,Pyrexia,25.0,Red blood cell count increased,25.0,Renal function test,25.0,Rhesus antigen positive,25.0
2999606,2304026,Rheumatoid factor negative,25.0,Right atrial enlargement,25.0,Right ventricular enlargement,25.0,Right ventricular failure,25.0,Scleral discolouration,25.0
2999607,2304026,Seizure,25.0,Serum ferritin increased,25.0,Skin lesion,25.0,Smooth muscle antibody negative,25.0,Splenomegaly,25.0
2999608,2304026,Systolic dysfunction,25.0,Thrombocytopenia,25.0,Tricuspid valve incompetence,25.0,Troponin I normal,25.0,Troponin T,25.0
2999609,2304026,Ultrasound Doppler abnormal,25.0,Ultrasound scan abnormal,25.0,Urinary incontinence,25.0,Urine protein/creatinine ratio,25.0,Ventricular hypertrophy,25.0
2999610,2304026,Ventricular hypoplasia,25.0,Viral test negative,25.0,Wall motion score index abnormal,25.0,Weight decreased,25.0,White blood cell count increased,25.0
2999611,2304026,White blood cell count normal,25.0,Yellow skin,25.0,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
v_vax.loc[v_vax['VAERS_ID'] == 2304026]

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
2750283,2304026,HPV9,MERCK & CO. INC.,T013848,1,NaN,LA,HPV (GARDASIL 9)
2750284,2304026,HPV9,MERCK & CO. INC.,T023175,2,NaN,RA,HPV (GARDASIL 9)
2750285,2304026,HPV9,MERCK & CO. INC.,T036299,3,NaN,LA,HPV (GARDASIL 9)
2750286,2304026,UNK,UNKNOWN MANUFACTURER,NaN,UNK,NaN,NaN,VACCINE NOT SPECIFIED (NO BRAND NAME)
2750287,2304026,UNK,UNKNOWN MANUFACTURER,NaN,UNK,NaN,NaN,VACCINE NOT SPECIFIED (NO BRAND NAME)
2750288,2304026,UNK,UNKNOWN MANUFACTURER,NaN,UNK,NaN,NaN,VACCINE NOT SPECIFIED (NO BRAND NAME)

In [65]:
v_data.loc[v_data['VAERS_ID'] == 2304026]

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,CUR_ILL,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES
2251139,2304026,06/01/2022,FR,19.0,NaN,NaN,F,NaN,megaloblastic anemia; convulsion; Alopecia; Th...,Y,...,Pulmonary arterial pressure decreased,NaN,NaN,CN0095075132205CHN007736,2,05/31/2022,NaN,NaN,NaN,NaN

In [67]:
tr = v_final.loc[v_final['VAERS_ID'] == 2304026]

In [72]:
tr.to_excel(r'C:/Users/lucky/Documents/Tutorial/PoC/vaers_id_2304026.xlsx', index=False)